<?php 
/** ESTADOS UF **/
$ufEstadoS = array (
/*	id	*/		null,
/*	1	*/		"AC",
/*	2	*/		"AL",
/*	3	*/		"AM",
/*	4	*/		"AP",
/*	5	*/		"BA",
/*	6	*/		"CE",
/*	7	*/		"DF",
/*	8	*/		"ES",
/*	9	*/		"GO",
/*	10	*/		"MA",
/*	11	*/		"MG",
/*	12	*/		"MS",
/*	13	*/		"MT",
/*	14	*/		"PA",
/*	15	*/		"PB",
/*	16	*/		"PE",
/*	17	*/		"PI",
/*	18	*/		"PR",
/*	19	*/		"RJ",
/*	20	*/		"RN",
/*	21	*/		"RO",
/*	22	*/		"RR",
/*	23	*/		"RS",
/*	24	*/		"SC",
/*	25	*/		"SE",
/*	26	*/		"SP",
/*	27	*/		"TO"
);

/** NACIONALIDADES **/
$nacionalidadeS = array(
/*	id	*/		null,
/*	1	*/		"Afeganistão",
/*	2	*/		"África do Sul",
/*	3	*/		"Albânia",
/*	4	*/		"Alemanha",
/*	5	*/		"Andorra",
/*	6	*/		"Angola",
/*	7	*/		"Anguilla",
/*	8	*/		"Antártica",
/*	9	*/		"Antígua e Barbuda",
/*	10	*/		"Antilhas Holandesas",
/*	11	*/		"Arábia Saudita",
/*	12	*/		"Argélia",
/*	13	*/		"Argentina",
/*	14	*/		"Armênia",
/*	15	*/		"Aruba",
/*	16	*/		"Austrália",
/*	17	*/		"Áustria",
/*	18	*/		"Azerbaijão",
/*	19	*/		"Bahamas",
/*	20	*/		"Bangladesh",
/*	21	*/		"Barbados",
/*	22	*/		"Barein",
/*	23	*/		"Belarus",
/*	24	*/		"Bélgica",
/*	25	*/		"Belize",
/*	26	*/		"Benin",
/*	27	*/		"Bermuda",
/*	28	*/		"Bolívia",
/*	29	*/		"Bósnia e Herzegovina",
/*	30	*/		"Botswana",
/*	31	*/		"Brasil",
/*	32	*/		"Brunei Darussalém",
/*	33	*/		"Bulgária",
/*	34	*/		"Burkina Fasso",
/*	35	*/		"Burundi",
/*	36	*/		"Butão",
/*	37	*/		"Cabo Verde",
/*	38	*/		"Camarões",
/*	39	*/		"Camboja",
/*	40	*/		"Canadá",
/*	41	*/		"Catar",
/*	42	*/		"Cazaquistão",
/*	43	*/		"Chade",
/*	44	*/		"Chile",
/*	45	*/		"China",
/*	46	*/		"Chipre",
/*	47	*/		"Cidade do Vaticano",
/*	48	*/		"Cingapura",
/*	49	*/		"Colômbia",
/*	50	*/		"Congo (Brazzaville)",
/*	51	*/		"Congo (Kinshasa)",
/*	52	*/		"Coréia do Norte",
/*	53	*/		"Coréia do Sul",
/*	54	*/		"Costa do Marfim",
/*	55	*/		"Costa Rica",
/*	56	*/		"Croácia",
/*	57	*/		"Cuba",
/*	58	*/		"Dinamarca",
/*	59	*/		"Djibuti",
/*	60	*/		"Dominica",
/*	61	*/		"Egito",
/*	62	*/		"El Salvador",
/*	63	*/		"Emirados Árabes Unidos",
/*	64	*/		"Equador",
/*	65	*/		"Eritréia",
/*	66	*/		"Eslováquia",
/*	67	*/		"Eslovênia",
/*	68	*/		"Espanha",
/*	69	*/		"Estados Unidos",
/*	70	*/		"Estônia",
/*	71	*/		"Etiópia",
/*	72	*/		"Fiji",
/*	73	*/		"Filipinas",
/*	74	*/		"Finlândia",
/*	75	*/		"França",
/*	76	*/		"França Metropolitana",
/*	77	*/		"Gabão",
/*	78	*/		"Gâmbia",
/*	79	*/		"Gana",
/*	80	*/		"Geórgia",
/*	81	*/		"Geórgia do Sul e Ilhas Sandwich",
/*	82	*/		"Gibraltar",
/*	83	*/		"Granada",
/*	84	*/		"Grécia",
/*	85	*/		"Groelândia",
/*	86	*/		"Guadalupe",
/*	87	*/		"Guam",
/*	88	*/		"Guatemala",
/*	89	*/		"Guiana",
/*	90	*/		"Guiana Francesa",
/*	91	*/		"Guiné",
/*	92	*/		"Guiné Equatorial",
/*	93	*/		"Guiné-Bissau",
/*	94	*/		"Haiti",
/*	95	*/		"Holanda",
/*	96	*/		"Honduras",
/*	97	*/		"Hong Kong",
/*	98	*/		"Hungria",
/*	99	*/		"Iêmen",
/*	100	*/		"Ilha Bouvet",
/*	101	*/		"Ilha Norfolk",
/*	102	*/		"Ilha Reunião",
/*	103	*/		"Ilhas Cayman",
/*	104	*/		"Ilhas Christmas",
/*	105	*/		"Ilhas Cocos",
/*	106	*/		"Ilhas Comores",
/*	107	*/		"Ilhas Cook",
/*	108	*/		"Ilhas Falkland (Malvinas)",
/*	109	*/		"Ilhas Feroé",
/*	110	*/		"Ilhas Heard e Mcdonald",
/*	111	*/		"Ilhas Marianas do Norte",
/*	112	*/		"Ilhas Marshall",
/*	113	*/		"Ilhas Salomão",
/*	114	*/		"Ilhas Svalbard e Jan Mayen",
/*	115	*/		"Ilhas Turks e Caicos",
/*	116	*/		"Ilhas Virgens Americanas",
/*	117	*/		"Ilhas Virgens Britânicas",
/*	118	*/		"Ilhas Wallis e Futuna",
/*	119	*/		"Índia",
/*	120	*/		"Indonésia",
/*	121	*/		"Irã",
/*	122	*/		"Iraque",
/*	123	*/		"Irlanda",
/*	124	*/		"Islândia",
/*	125	*/		"Israel",
/*	126	*/		"Itália",
/*	127	*/		"Jamaica",
/*	128	*/		"Japão",
/*	129	*/		"Jordânia",
/*	130	*/		"Kiribati",
/*	131	*/		"Kuwait",
/*	132	*/		"Laos",
/*	133	*/		"Lesoto",
/*	134	*/		"Letônia",
/*	135	*/		"Líbano",
/*	136	*/		"Libéria",
/*	137	*/		"Líbia",
/*	138	*/		"Liechtenstein",
/*	139	*/		"Lituânia",
/*	140	*/		"Luxemburgo",
/*	141	*/		"Macau",
/*	142	*/		"Macedônia",
/*	143	*/		"Madagascar",
/*	144	*/		"Malásia",
/*	145	*/		"Malavi",
/*	146	*/		"Maldivas",
/*	147	*/		"Mali",
/*	148	*/		"Malta",
/*	149	*/		"Marrocos",
/*	150	*/		"Martinica",
/*	151	*/		"Maurício",
/*	152	*/		"Mauritânia",
/*	153	*/		"Mayotte",
/*	154	*/		"México",
/*	155	*/		"Micronésia",
/*	156	*/		"Moçambique",
/*	157	*/		"Moldávia",
/*	158	*/		"Mônaco",
/*	159	*/		"Mongólia",
/*	160	*/		"Montenegro",
/*	161	*/		"Montserrat",
/*	162	*/		"Myanma",
/*	163	*/		"Namíbia",
/*	164	*/		"Nauru",
/*	165	*/		"Nepal",
/*	166	*/		"Nicarágua",
/*	167	*/		"Níger",
/*	168	*/		"Nigéria",
/*	169	*/		"Niue",
/*	170	*/		"Noruega",
/*	171	*/		"Nova Caledônia",
/*	172	*/		"Nova Zelândia",
/*	173	*/		"Omã",
/*	174	*/		"Palau",
/*	175	*/		"Panamá",
/*	176	*/		"Papua-Nova Guiné",
/*	177	*/		"Paquistão",
/*	178	*/		"Paraguai",
/*	179	*/		"Peru",
/*	180	*/		"Pitcairn",
/*	181	*/		"Polinésia Francesa",
/*	182	*/		"Polônia",
/*	183	*/		"Porto Rico",
/*	184	*/		"Portugal",
/*	185	*/		"Quênia",
/*	186	*/		"Quirguistão",
/*	187	*/		"Reino Unido",
/*	188	*/		"República Centro-Africana",
/*	189	*/		"República Dominicana",
/*	190	*/		"República Tcheca",
/*	191	*/		"Romênia",
/*	192	*/		"Ruanda",
/*	193	*/		"Russia",
/*	194	*/		"Saara Ocidental",
/*	195	*/		"Saint Kitts e Nevis",
/*	196	*/		"Saint Pierre e Miquelon",
/*	197	*/		"Samoa",
/*	198	*/		"Samoa Americana",
/*	199	*/		"Santa Helena",
/*	200	*/		"Santa Lúcia",
/*	201	*/		"São Marino",
/*	202	*/		"São Tomé e Príncipe",
/*	203	*/		"São Vicente e Granadinas",
/*	204	*/		"Senegal",
/*	205	*/		"Serra Leoa",
/*	206	*/		"Sérvia",
/*	207	*/		"Seychelles",
/*	208	*/		"Síria",
/*	209	*/		"Somália",
/*	210	*/		"Sri Lanka",
/*	211	*/		"Suazilândia",
/*	212	*/		"Sudão",
/*	213	*/		"Suécia",
/*	214	*/		"Suíça",
/*	215	*/		"Suriname",
/*	216	*/		"Tadjiquistão",
/*	217	*/		"Tailândia",
/*	218	*/		"Taiwan",
/*	219	*/		"Tanzânia",
/*	220	*/		"Territórios Britânicos do Oceano Índico",
/*	221	*/		"Territórios Franceses do Sul",
/*	222	*/		"Territórios Insulares dos Estados Unidos",
/*	223	*/		"Timor Oriental",
/*	224	*/		"Togo",
/*	225	*/		"Tokelau",
/*	226	*/		"Tonga",
/*	227	*/		"Trinidad e Tobago",
/*	228	*/		"Tunísia",
/*	229	*/		"Turcomenistão",
/*	230	*/		"Turquia",
/*	231	*/		"Tuvalu",
/*	232	*/		"Ucrânia",
/*	233	*/		"Uganda",
/*	234	*/		"Uruguai",
/*	235	*/		"Uzbequistão",
/*	236	*/		"Vanuatu",
/*	237	*/		"Venezuela",
/*	238	*/		"Vietnã",
/*	239	*/		"Zâmbia",
/*	240	*/		"Zimbabwe" );

/** CIDADES **/
	$cidadeS = array (
/*	id	*/		null,
/*	1	*/		"Adamantina",
/*	2	*/		"Adolfo",
/*	3	*/		"Aguaí",
/*	4	*/		"Águas da Prata",
/*	5	*/		"Águas de Lindóia",
/*	6	*/		"Águas de Santa Bárbara",
/*	7	*/		"Águas de São Pedro",
/*	8	*/		"Agudos",
/*	9	*/		"Alambari",
/*	10	*/		"Alfredo Marcondes",
/*	11	*/		"Altair",
/*	12	*/		"Altinópolis",
/*	13	*/		"Alto Alegre",
/*	14	*/		"Alumínio",
/*	15	*/		"Álvares Florence",
/*	16	*/		"Álvares Machado",
/*	17	*/		"Álvaro de Carvalho",
/*	18	*/		"Alvinlândia",
/*	19	*/		"Americana",
/*	20	*/		"Américo Brasiliense",
/*	21	*/		"Américo de Campos",
/*	22	*/		"Amparo",
/*	23	*/		"Analândia",
/*	24	*/		"Andradina",
/*	25	*/		"Angatuba",
/*	26	*/		"Anhembi",
/*	27	*/		"Anhumas",
/*	28	*/		"Aparecida",
/*	29	*/		"Aparecida d'Oeste",
/*	30	*/		"Apiaí",
/*	31	*/		"Araçariguama",
/*	32	*/		"Araçatuba",
/*	33	*/		"Araçoiaba da Serra",
/*	34	*/		"Aramina",
/*	35	*/		"Arandu",
/*	36	*/		"Arapeí",
/*	37	*/		"Araraquara",
/*	38	*/		"Araras",
/*	39	*/		"Arco-Íris",
/*	40	*/		"Arealva",
/*	41	*/		"Areias",
/*	42	*/		"Areiópolis",
/*	43	*/		"Ariranha",
/*	44	*/		"Artur Nogueira",
/*	45	*/		"Arujá",
/*	46	*/		"Aspásia",
/*	47	*/		"Assis",
/*	48	*/		"Atibaia",
/*	49	*/		"Auriflama",
/*	50	*/		"Avaí",
/*	51	*/		"Avanhandava",
/*	52	*/		"Avaré",
/*	53	*/		"Bady Bassitt",
/*	54	*/		"Balbinos",
/*	55	*/		"Bálsamo",
/*	56	*/		"Bananal",
/*	57	*/		"Barão de Antonina",
/*	58	*/		"Barbosa",
/*	59	*/		"Bariri",
/*	60	*/		"Barra Bonita",
/*	61	*/		"Barra do Chapéu",
/*	62	*/		"Barra do Turvo",
/*	63	*/		"Barretos",
/*	64	*/		"Barrinha",
/*	65	*/		"Barueri",
/*	66	*/		"Bastos",
/*	67	*/		"Batatais",
/*	68	*/		"Bauru",
/*	69	*/		"Bebedouro",
/*	70	*/		"Bento de Abreu",
/*	71	*/		"Bernardino de Campos",
/*	72	*/		"Bertioga",
/*	73	*/		"Bilac",
/*	74	*/		"Birigui",
/*	75	*/		"Biritiba-Mirim",
/*	76	*/		"Boa Esperança do Sul",
/*	77	*/		"Bocaina",
/*	78	*/		"Bofete",
/*	79	*/		"Boituva",
/*	80	*/		"Bom Jesus dos Perdões",
/*	81	*/		"Bom Sucesso de Itararé",
/*	82	*/		"Borá",
/*	83	*/		"Boracéia",
/*	84	*/		"Borborema",
/*	85	*/		"Borebi",
/*	86	*/		"Botucatu",
/*	87	*/		"Bragança Paulista",
/*	88	*/		"Braúna",
/*	89	*/		"Brejo Alegre",
/*	90	*/		"Brodowski",
/*	91	*/		"Brotas",
/*	92	*/		"Buri",
/*	93	*/		"Buritama",
/*	94	*/		"Buritizal",
/*	95	*/		"Cabrália Paulista",
/*	96	*/		"Cabreúva",
/*	97	*/		"Caçapava",
/*	98	*/		"Cachoeira Paulista",
/*	99	*/		"Caconde",
/*	100	*/		"Cafelândia",
/*	101	*/		"Caiabu",
/*	102	*/		"Caieiras",
/*	103	*/		"Caiuá",
/*	104	*/		"Cajamar",
/*	105	*/		"Cajati",
/*	106	*/		"Cajobi",
/*	107	*/		"Cajuru",
/*	108	*/		"Campina do Monte Alegre",
/*	109	*/		"Campinas",
/*	110	*/		"Campo Limpo Paulista",
/*	111	*/		"Campos do Jordão",
/*	112	*/		"Campos Novos Paulista",
/*	113	*/		"Cananéia",
/*	114	*/		"Canas",
/*	115	*/		"Cândido Mota",
/*	116	*/		"Cândido Rodrigues",
/*	117	*/		"Canitar",
/*	118	*/		"Capão Bonito",
/*	119	*/		"Capela do Alto",
/*	120	*/		"Capivari",
/*	121	*/		"Caraguatatuba",
/*	122	*/		"Carapicuíba",
/*	123	*/		"Cardoso",
/*	124	*/		"Casa Branca",
/*	125	*/		"Cássia dos Coqueiros",
/*	126	*/		"Castilho",
/*	127	*/		"Catanduva",
/*	128	*/		"Catiguá",
/*	129	*/		"Cedral",
/*	130	*/		"Cerqueira César",
/*	131	*/		"Cerquilho",
/*	132	*/		"Cesário Lange",
/*	133	*/		"Charqueada",
/*	134	*/		"Chavantes",
/*	135	*/		"Clementina",
/*	136	*/		"Colina",
/*	137	*/		"Colômbia",
/*	138	*/		"Conchal",
/*	139	*/		"Conchas",
/*	140	*/		"Cordeirópolis",
/*	141	*/		"Coroados",
/*	142	*/		"Coronel Macedo",
/*	143	*/		"Corumbataí",
/*	144	*/		"Cosmópolis",
/*	145	*/		"Cosmorama",
/*	146	*/		"Cotia",
/*	147	*/		"Cravinhos",
/*	148	*/		"Cristais Paulista",
/*	149	*/		"Cruzália",
/*	150	*/		"Cruzeiro",
/*	151	*/		"Cubatão",
/*	152	*/		"Cunha",
/*	153	*/		"Descalvado",
/*	154	*/		"Diadema",
/*	155	*/		"Dirce Reis",
/*	156	*/		"Divinolândia",
/*	157	*/		"Dobrada",
/*	158	*/		"Dois Córregos",
/*	159	*/		"Dolcinópolis",
/*	160	*/		"Dourado",
/*	161	*/		"Dracena",
/*	162	*/		"Duartina",
/*	163	*/		"Dumont",
/*	164	*/		"Echaporã",
/*	165	*/		"Eldorado",
/*	166	*/		"Elias Fausto",
/*	167	*/		"Elisiário",
/*	168	*/		"Embaúba",
/*	169	*/		"Embu",
/*	170	*/		"Embu-Guaçu",
/*	171	*/		"Emilianópolis",
/*	172	*/		"Engenheiro Coelho",
/*	173	*/		"Espírito Santo do Pinhal",
/*	174	*/		"Espírito Santo do Turvo",
/*	175	*/		"Estiva Gerbi",
/*	176	*/		"Estrela do Norte",
/*	177	*/		"Estrela d'Oeste",
/*	178	*/		"Euclides da Cunha Paulista",
/*	179	*/		"Fartura",
/*	180	*/		"Fernando Prestes",
/*	181	*/		"Fernandópolis",
/*	182	*/		"Fernão",
/*	183	*/		"Ferraz de Vasconcelos",
/*	184	*/		"Flora Rica",
/*	185	*/		"Floreal",
/*	186	*/		"Flórida Paulista",
/*	187	*/		"Florínea",
/*	188	*/		"Franca",
/*	189	*/		"Francisco Morato",
/*	190	*/		"Franco da Rocha",
/*	191	*/		"Gabriel Monteiro",
/*	192	*/		"Gália",
/*	193	*/		"Garça",
/*	194	*/		"Gastão Vidigal",
/*	195	*/		"Gavião Peixoto",
/*	196	*/		"General Salgado",
/*	197	*/		"Getulina",
/*	198	*/		"Glicério",
/*	199	*/		"Guaiçara",
/*	200	*/		"Guaimbê",
/*	201	*/		"Guaíra",
/*	202	*/		"Guapiaçu",
/*	203	*/		"Guapiara",
/*	204	*/		"Guará",
/*	205	*/		"Guaraçaí",
/*	206	*/		"Guaraci",
/*	207	*/		"Guarani d'Oeste",
/*	208	*/		"Guarantã",
/*	209	*/		"Guararapes",
/*	210	*/		"Guararema",
/*	211	*/		"Guaratinguetá",
/*	212	*/		"Guareí",
/*	213	*/		"Guariba",
/*	214	*/		"Guarujá",
/*	215	*/		"Guarulhos",
/*	216	*/		"Guatapará",
/*	217	*/		"Guzolândia",
/*	218	*/		"Herculândia",
/*	219	*/		"Holambra",
/*	220	*/		"Hortolândia",
/*	221	*/		"Iacanga",
/*	222	*/		"Iacri",
/*	223	*/		"Iaras",
/*	224	*/		"Ibaté",
/*	225	*/		"Ibirá",
/*	226	*/		"Ibirarema",
/*	227	*/		"Ibitinga",
/*	228	*/		"Ibiúna",
/*	229	*/		"Icém",
/*	230	*/		"Iepê",
/*	231	*/		"Igaraçu do Tietê",
/*	232	*/		"Igarapava",
/*	233	*/		"Igaratá",
/*	234	*/		"Iguape",
/*	235	*/		"Ilha Comprida",
/*	236	*/		"Ilha Solteira",
/*	237	*/		"Ilhabela",
/*	238	*/		"Indaiatuba",
/*	239	*/		"Indiana",
/*	240	*/		"Indiaporã",
/*	241	*/		"Inúbia Paulista",
/*	242	*/		"Ipaussu",
/*	243	*/		"Iperó",
/*	244	*/		"Ipeúna",
/*	245	*/		"Ipiguá",
/*	246	*/		"Iporanga",
/*	247	*/		"Ipuã",
/*	248	*/		"Iracemápolis",
/*	249	*/		"Irapuã",
/*	250	*/		"Irapuru",
/*	251	*/		"Itaberá",
/*	252	*/		"Itaí",
/*	253	*/		"Itajobi",
/*	254	*/		"Itaju",
/*	255	*/		"Itanhaém",
/*	256	*/		"Itaóca",
/*	257	*/		"Itapecerica da Serra",
/*	258	*/		"Itapetininga",
/*	259	*/		"Itapeva",
/*	260	*/		"Itapevi",
/*	261	*/		"Itapira",
/*	262	*/		"Itapirapuã Paulista",
/*	263	*/		"Itápolis",
/*	264	*/		"Itaporanga",
/*	265	*/		"Itapuí",
/*	266	*/		"Itapura",
/*	267	*/		"Itaquaquecetuba",
/*	268	*/		"Itararé",
/*	269	*/		"Itariri",
/*	270	*/		"Itatiba",
/*	271	*/		"Itatinga",
/*	272	*/		"Itirapina",
/*	273	*/		"Itirapuã",
/*	274	*/		"Itobi",
/*	275	*/		"Itu",
/*	276	*/		"Itupeva",
/*	277	*/		"Ituverava",
/*	278	*/		"Jaborandi",
/*	279	*/		"Jaboticabal",
/*	280	*/		"Jacareí",
/*	281	*/		"Jaci",
/*	282	*/		"Jacupiranga",
/*	283	*/		"Jaguariúna",
/*	284	*/		"Jales",
/*	285	*/		"Jambeiro",
/*	286	*/		"Jandira",
/*	287	*/		"Jardinópolis",
/*	288	*/		"Jarinu",
/*	289	*/		"Jaú",
/*	290	*/		"Jeriquara",
/*	291	*/		"Joanópolis",
/*	292	*/		"João Ramalho",
/*	293	*/		"José Bonifácio",
/*	294	*/		"Júlio Mesquita",
/*	295	*/		"Jumirim",
/*	296	*/		"Jundiaí",
/*	297	*/		"Junqueirópolis",
/*	298	*/		"Juquiá",
/*	299	*/		"Juquitiba",
/*	300	*/		"Lagoinha",
/*	301	*/		"Laranjal Paulista",
/*	302	*/		"Lavínia",
/*	303	*/		"Lavrinhas",
/*	304	*/		"Leme",
/*	305	*/		"Lençóis Paulista",
/*	306	*/		"Limeira",
/*	307	*/		"Lindóia",
/*	308	*/		"Lins",
/*	309	*/		"Lorena",
/*	310	*/		"Lourdes",
/*	311	*/		"Louveira",
/*	312	*/		"Lucélia",
/*	313	*/		"Lucianópolis",
/*	314	*/		"Luís Antônio",
/*	315	*/		"Luiziânia",
/*	316	*/		"Lupércio",
/*	317	*/		"Lutécia",
/*	318	*/		"Macatuba",
/*	319	*/		"Macaubal",
/*	320	*/		"Macedônia",
/*	321	*/		"Magda",
/*	322	*/		"Mairinque",
/*	323	*/		"Mairiporã",
/*	324	*/		"Manduri",
/*	325	*/		"Marabá Paulista",
/*	326	*/		"Maracaí",
/*	327	*/		"Marapoama",
/*	328	*/		"Mariápolis",
/*	329	*/		"Marília",
/*	330	*/		"Marinópolis",
/*	331	*/		"Martinópolis",
/*	332	*/		"Matão",
/*	333	*/		"Mauá",
/*	334	*/		"Mendonça",
/*	335	*/		"Meridiano",
/*	336	*/		"Mesópolis",
/*	337	*/		"Miguelópolis",
/*	338	*/		"Mineiros do Tietê",
/*	339	*/		"Mira Estrela",
/*	340	*/		"Miracatu",
/*	341	*/		"Mirandópolis",
/*	342	*/		"Mirante do Paranapanema",
/*	343	*/		"Mirassol",
/*	344	*/		"Mirassolândia",
/*	345	*/		"Mococa",
/*	346	*/		"Mogi das Cruzes",
/*	347	*/		"Mogi-Guaçu",
/*	348	*/		"Mogi-Mirim",
/*	349	*/		"Mombuca",
/*	350	*/		"Monções",
/*	351	*/		"Mongaguá",
/*	352	*/		"Monte Alegre do Sul",
/*	353	*/		"Monte Alto",
/*	354	*/		"Monte Aprazível",
/*	355	*/		"Monte Azul Paulista",
/*	356	*/		"Monte Castelo",
/*	357	*/		"Monte Mor",
/*	358	*/		"Monteiro Lobato",
/*	359	*/		"Morro Agudo",
/*	360	*/		"Morungaba",
/*	361	*/		"Motuca",
/*	362	*/		"Murutinga do Sul",
/*	363	*/		"Nantes",
/*	364	*/		"Narandiba",
/*	365	*/		"Natividade da Serra",
/*	366	*/		"Nazaré Paulista",
/*	367	*/		"Neves Paulista",
/*	368	*/		"Nhandeara",
/*	369	*/		"Nipoã",
/*	370	*/		"Nova Aliança",
/*	371	*/		"Nova Campina",
/*	372	*/		"Nova Canaã Paulista",
/*	373	*/		"Nova Castilho",
/*	374	*/		"Nova Europa",
/*	375	*/		"Nova Granada",
/*	376	*/		"Nova Guataporanga",
/*	377	*/		"Nova Independência",
/*	378	*/		"Nova Luzitânia",
/*	379	*/		"Nova Odessa",
/*	380	*/		"Novais",
/*	381	*/		"Novo Horizonte",
/*	382	*/		"Nuporanga",
/*	383	*/		"Ocauçu",
/*	384	*/		"Óleo",
/*	385	*/		"Olímpia",
/*	386	*/		"Onda Verde",
/*	387	*/		"Oriente",
/*	388	*/		"Orindiúva",
/*	389	*/		"Orlândia",
/*	390	*/		"Osasco",
/*	391	*/		"Oscar Bressane",
/*	392	*/		"Osvaldo Cruz",
/*	393	*/		"Ourinhos",
/*	394	*/		"Ouro Verde",
/*	395	*/		"Ouroeste",
/*	396	*/		"Pacaembu",
/*	397	*/		"Palestina",
/*	398	*/		"Palmares Paulista",
/*	399	*/		"Palmeira d'Oeste",
/*	400	*/		"Palmital",
/*	401	*/		"Panorama",
/*	402	*/		"Paraguaçu Paulista",
/*	403	*/		"Paraibuna",
/*	404	*/		"Paraíso",
/*	405	*/		"Paranapanema",
/*	406	*/		"Paranapuã",
/*	407	*/		"Parapuã",
/*	408	*/		"Pardinho",
/*	409	*/		"Pariquera-Açu",
/*	410	*/		"Parisi",
/*	411	*/		"Patrocínio Paulista",
/*	412	*/		"Paulicéia",
/*	413	*/		"Paulínia",
/*	414	*/		"Paulistânia",
/*	415	*/		"Paulo de Faria",
/*	416	*/		"Pederneiras",
/*	417	*/		"Pedra Bela",
/*	418	*/		"Pedranópolis",
/*	419	*/		"Pedregulho",
/*	420	*/		"Pedreira",
/*	421	*/		"Pedrinhas Paulista",
/*	422	*/		"Pedro de Toledo",
/*	423	*/		"Penápolis",
/*	424	*/		"Pereira Barreto",
/*	425	*/		"Pereiras",
/*	426	*/		"Peruíbe",
/*	427	*/		"Piacatu",
/*	428	*/		"Piedade",
/*	429	*/		"Pilar do Sul",
/*	430	*/		"Pindamonhangaba",
/*	431	*/		"Pindorama",
/*	432	*/		"Pinhalzinho",
/*	433	*/		"Piquerobi",
/*	434	*/		"Piquete",
/*	435	*/		"Piracaia",
/*	436	*/		"Piracicaba",
/*	437	*/		"Piraju",
/*	438	*/		"Pirajuí",
/*	439	*/		"Pirangi",
/*	440	*/		"Pirapora do Bom Jesus",
/*	441	*/		"Pirapozinho",
/*	442	*/		"Pirassununga",
/*	443	*/		"Piratininga",
/*	444	*/		"Pitangueiras",
/*	445	*/		"Planalto",
/*	446	*/		"Platina",
/*	447	*/		"Poá",
/*	448	*/		"Poloni",
/*	449	*/		"Pompéia",
/*	450	*/		"Pongaí",
/*	451	*/		"Pontal",
/*	452	*/		"Pontalinda",
/*	453	*/		"Pontes Gestal",
/*	454	*/		"Populina",
/*	455	*/		"Porangaba",
/*	456	*/		"Porto Feliz",
/*	457	*/		"Porto Ferreira",
/*	458	*/		"Potim",
/*	459	*/		"Potirendaba",
/*	460	*/		"Pracinha",
/*	461	*/		"Pradópolis",
/*	462	*/		"Praia Grande",
/*	463	*/		"Pratânia",
/*	464	*/		"Presidente Alves",
/*	465	*/		"Presidente Bernardes",
/*	466	*/		"Presidente Epitácio",
/*	467	*/		"Presidente Prudente",
/*	468	*/		"Presidente Venceslau",
/*	469	*/		"Promissão",
/*	470	*/		"Quadra",
/*	471	*/		"Quatá",
/*	472	*/		"Queiroz",
/*	473	*/		"Queluz",
/*	474	*/		"Quintana",
/*	475	*/		"Rafard",
/*	476	*/		"Rancharia",
/*	477	*/		"Redenção da Serra",
/*	478	*/		"Regente Feijó",
/*	479	*/		"Reginópolis",
/*	480	*/		"Registro",
/*	481	*/		"Restinga",
/*	482	*/		"Ribeira",
/*	483	*/		"Ribeirão Bonito",
/*	484	*/		"Ribeirão Branco",
/*	485	*/		"Ribeirão Corrente",
/*	486	*/		"Ribeirão do Sul",
/*	487	*/		"Ribeirão dos Índios",
/*	488	*/		"Ribeirão Grande",
/*	489	*/		"Ribeirão Pires",
/*	490	*/		"Ribeirão Preto",
/*	491	*/		"Rifaina",
/*	492	*/		"Rincão",
/*	493	*/		"Rinópolis",
/*	494	*/		"Rio Claro",
/*	495	*/		"Rio das Pedras",
/*	496	*/		"Rio Grande da Serra",
/*	497	*/		"Riolândia",
/*	498	*/		"Riversul",
/*	499	*/		"Rosana",
/*	500	*/		"Roseira",
/*	501	*/		"Rubiácea",
/*	502	*/		"Rubinéia",
/*	503	*/		"Sabino",
/*	504	*/		"Sagres",
/*	505	*/		"Sales",
/*	506	*/		"Sales Oliveira",
/*	507	*/		"Salesópolis",
/*	508	*/		"Salmourão",
/*	509	*/		"Saltinho",
/*	510	*/		"Salto",
/*	511	*/		"Salto de Pirapora",
/*	512	*/		"Salto Grande",
/*	513	*/		"Sandovalina",
/*	514	*/		"Santa Adélia",
/*	515	*/		"Santa Albertina",
/*	516	*/		"Santa Bárbara d'Oeste",
/*	517	*/		"Santa Branca",
/*	518	*/		"Santa Clara d'Oeste",
/*	519	*/		"Santa Cruz da Conceição",
/*	520	*/		"Santa Cruz da Esperança",
/*	521	*/		"Santa Cruz das Palmeiras",
/*	522	*/		"Santa Cruz do Rio Pardo",
/*	523	*/		"Santa Ernestina",
/*	524	*/		"Santa Fé do Sul",
/*	525	*/		"Santa Gertrudes",
/*	526	*/		"Santa Isabel",
/*	527	*/		"Santa Lúcia",
/*	528	*/		"Santa Maria da Serra",
/*	529	*/		"Santa Mercedes",
/*	530	*/		"Santa Rita do Passa Quatro",
/*	531	*/		"Santa Rita d'Oeste",
/*	532	*/		"Santa Rosa de Viterbo",
/*	533	*/		"Santa Salete",
/*	534	*/		"Santana da Ponte Pensa",
/*	535	*/		"Santana de Parnaíba",
/*	536	*/		"Santo Anastácio",
/*	537	*/		"Santo André",
/*	538	*/		"Santo Antônio da Alegria",
/*	539	*/		"Santo Antônio de Posse",
/*	540	*/		"Santo Antônio do Aracangua",
/*	541	*/		"Santo Antônio do Jardim",
/*	542	*/		"Santo Antônio do Pinhal",
/*	543	*/		"Santo Expedito",
/*	544	*/		"Santópolis do Aguapeí",
/*	545	*/		"Santos",
/*	546	*/		"São Bento do Sapucaí",
/*	547	*/		"São Bernardo do Campo",
/*	548	*/		"São Caetano do Sul",
/*	549	*/		"São Carlos",
/*	550	*/		"São Francisco",
/*	551	*/		"São João da Boa Vista",
/*	552	*/		"São João das Duas Pontes",
/*	553	*/		"São João de Iracema",
/*	554	*/		"São João do Pau d'Alho",
/*	555	*/		"São Joaquim da Barra",
/*	556	*/		"São José da Bela Vista",
/*	557	*/		"São José do Barreiro",
/*	558	*/		"São José do Rio Pardo",
/*	559	*/		"São José do Rio Preto",
/*	560	*/		"São José dos Campos",
/*	561	*/		"São Lourenço da Serra",
/*	562	*/		"São Luís do Paraitinga",
/*	563	*/		"São Manuel",
/*	564	*/		"São Miguel Arcanjo",
/*	565	*/		"São Paulo",
/*	566	*/		"São Pedro",
/*	567	*/		"São Pedro do Turvo",
/*	568	*/		"São Roque",
/*	569	*/		"São Sebastião",
/*	570	*/		"São Sebastião da Grama",
/*	571	*/		"São Simão",
/*	572	*/		"São Vicente",
/*	573	*/		"Sarapuí",
/*	574	*/		"Sarutaiá",
/*	575	*/		"Sebastianópolis do Sul",
/*	576	*/		"Serra Azul",
/*	577	*/		"Serra Negra",
/*	578	*/		"Serrana",
/*	579	*/		"Sertãozinho",
/*	580	*/		"Sete Barras",
/*	581	*/		"Severínia",
/*	582	*/		"Silveiras",
/*	583	*/		"Socorro",
/*	584	*/		"Sorocaba",
/*	585	*/		"Sud Mennucci",
/*	586	*/		"Sumaré",
/*	587	*/		"Suzanápolis",
/*	588	*/		"Suzano",
/*	589	*/		"Tabapuã",
/*	590	*/		"Tabatinga",
/*	591	*/		"Taboão da Serra",
/*	592	*/		"Taciba",
/*	593	*/		"Taguaí",
/*	594	*/		"Taiaçu",
/*	595	*/		"Taiúva",
/*	596	*/		"Tambaú",
/*	597	*/		"Tanabi",
/*	598	*/		"Tapiraí",
/*	599	*/		"Tapiratiba",
/*	600	*/		"Taquaral",
/*	601	*/		"Taquaritinga",
/*	602	*/		"Taquarituba",
/*	603	*/		"Taquarivaí",
/*	604	*/		"Tarabai",
/*	605	*/		"Tarumã",
/*	606	*/		"Tatuí",
/*	607	*/		"Taubaté",
/*	608	*/		"Tejupá",
/*	609	*/		"Teodoro Sampaio",
/*	610	*/		"Terra Roxa",
/*	611	*/		"Tietê",
/*	612	*/		"Timburi",
/*	613	*/		"Torre de Pedra",
/*	614	*/		"Torrinha",
/*	615	*/		"Trabiju",
/*	616	*/		"Tremembé",
/*	617	*/		"Três Fronteiras",
/*	618	*/		"Tuiuti",
/*	619	*/		"Tupã",
/*	620	*/		"Tupi Paulista",
/*	621	*/		"Turiúba",
/*	622	*/		"Turmalina",
/*	623	*/		"Ubarana",
/*	624	*/		"Ubatuba",
/*	625	*/		"Ubirajara",
/*	626	*/		"Uchoa",
/*	627	*/		"União Paulista",
/*	628	*/		"Urânia",
/*	629	*/		"Uru",
/*	630	*/		"Urupês",
/*	631	*/		"Valentim Gentil",
/*	632	*/		"Valinhos",
/*	633	*/		"Valparaíso",
/*	634	*/		"Vargem",
/*	635	*/		"Vargem Grande do Sul",
/*	636	*/		"Vargem Grande Paulista",
/*	637	*/		"Várzea Paulista",
/*	638	*/		"Vera Cruz",
/*	639	*/		"Vinhedo",
/*	640	*/		"Viradouro",
/*	641	*/		"Vista Alegre do Alto",
/*	642	*/		"Vitória Brasil",
/*	643	*/		"Votorantim",
/*	644	*/		"Votuporanga",
/*	645	*/		"Zacarias" );
	
/** Nivel de Escolaridade **/
$escolaridadeS = array (
/*	id	*/		null,
/*	1	*/		"Ensino Fundamental (1º Grau) interrompido",
/*	2	*/		"Ensino Fundamental (1º Grau) cursando",
/*	3	*/		"Ensino Fundamental (1º Grau) completo",
/*	4	*/		"Ensino Médio (2º Grau) interrompido",
/*	5	*/		"Ensino Médio (2º Grau) cursando",
/*	6	*/		"Ensino Médio (2º Grau) Profissionalizante cursando",
/*	7	*/		"Ensino Médio (2º Grau) completo",
/*	8	*/		"Ensino Médio (2º Grau) Profissionalizante completo",
/*	9	*/		"Formação Superior interrompida",
/*	10	*/		"Formação Superior (cursando)",
/*	11	*/		"Formação Superior Completa",
/*	12	*/		"Pós-Graduação no nível Especialização",
/*	13	*/		"Pós-Graduação no nível Mestrado",
/*	14	*/		"Pós-Graduação no nível Doutorado" );


/** Nivel de Escolaridade **/
$tipoCursoS = array (
/*	id	*/		null,
/*	1	*/		"Formação Escolar fundamental (1º Grau) e Média (2º Grau)",
/*	2	*/		"Curso Técnico – Médio (2º Grau)",
/*	3	*/		"Graduação",
/*	4	*/		"Pós-Graduação – Especialização",
/*	5	*/		"Pós-Graduação – MBA",
/*	6	*/		"Pós-Graduação – Mestrado",
/*	7	*/		"Pós-Graduação – Doutorado",
/*	8	*/		"Cursos Complementares" );

$estadoCivilS = array (
/*	id	*/		null,
/*	1	*/		"Solteiro(a)",
/*	2	*/		"Casado(a)",
/*	3	*/		"Separado(a)",
/*	4	*/		"Divorciado(a)",
/*	5	*/		"Viúvo(a)" );

/** NIVEIS DE IDIOMA **/
$nivelIdiomaS = array (
/*	id	*/		null,
/*	1	*/		"(Não tem)",
/*	2	*/		"Básica",
/*	3	*/		"Intermediária",
/*	4	*/		"Avançada",
/*	5	*/		"Fluente" );

/** IDIOMAS **/
$listaIdiomaS = array (
/*	id	*/		null,
/*	1	*/		"Africânder",
/*	2	*/		"Albanês",
/*	3	*/		"Alemão",
/*	4	*/		"Árabe",
/*	5	*/		"Azeri",
/*	6	*/		"Bengalês",
/*	7	*/		"Bielorusso",
/*	8	*/		"Búlgaro",
/*	9	*/		"Checo",
/*	10	*/		"Chinês (cantonês)",
/*	11	*/		"Chinês (mandarim)",
/*	12	*/		"Coreano",
/*	13	*/		"Croata",
/*	14	*/		"Dinamarquês",
/*	15	*/		"Escocês",
/*	16	*/		"Eslovaco",
/*	17	*/		"Esloveno",
/*	18	*/		"Espanhol",
/*	19	*/		"Estônio",
/*	20	*/		"Farsi",
/*	21	*/		"Finlandês",
/*	22	*/		"Francês",
/*	23	*/		"Georgiano",
/*	24	*/		"Grego",
/*	25	*/		"Hebraico",
/*	26	*/		"Hindi",
/*	27	*/		"Holandês",
/*	28	*/		"Húngaro",
/*	29	*/		"Indonésio",
/*	30	*/		"Inglês",
/*	31	*/		"Irlandês",
/*	32	*/		"Islandês",
/*	33	*/		"Italiano",
/*	34	*/		"Japonês",
/*	35	*/		"Lituano",
/*	36	*/		"Macedônio",
/*	37	*/		"Malaio",
/*	38	*/		"Mongol",
/*	39	*/		"Nepalês",
/*	40	*/		"Norueguês",
/*	41	*/		"Polaco",
/*	42	*/		"Português",
/*	43	*/		"Romeno",
/*	44	*/		"Russo",
/*	45	*/		"Sérvio",
/*	46	*/		"Sueco",
/*	47	*/		"Swahili",
/*	48	*/		"Tailandês",
/*	49	*/		"Tibetano",
/*	50	*/		"Turco",
/*	51	*/		"Ucraniano",
/*	52	*/		"Urdu",
/*	53	*/		"Usbeque",
/*	54	*/		"Vietnamita",
/*	55	*/		"Zulu"
);

/** NIVEIS INTERESSE **/
$nivelInteresseS = array (
/*	id	*/		null,
/*	1	*/		"Aprendiz",
/*	2	*/		"Auxiliar/Operacional",
/*	3	*/		"Técnico",
/*	4	*/		"Estágio",
/*	5	*/		"Júnior/Trainee",
/*	6	*/		"Pleno",
/*	7	*/		"Sênior",
/*	8	*/		"Supervisão/Coordenação",
/*	9	*/		"Vendas/Comercial",
/*	10	*/		"Gerência"
);

/** NIVEIS INTERESSE **/
$salarioS = array (
/*	id	*/		null,
/*	1	*/		"até R$999,99",
/*	2	*/		"de R$1.000 à R$1.999",
/*	3	*/		"de R$2.000 à R$2.999",
/*	4	*/		"de R$3.000 à R$3.999",
/*	5	*/		"de R$4.000 à R$4.999",
/*	6	*/		"de R$5.000 à R$6.999",
/*	7	*/		"de R$7.000 à R$9.999",
/*	8	*/		"acima de R$10.000"
);

/** STATUS AVALIAÇÃO **/
$statusAvaliacaoS = array (
/*	id	*/		null,
/*	1	*/		"Aprovado",
/*	2	*/		"Reprovado",
/*	3	*/		"Standby",
/*	4	*/		"Em processo",
/*	5	*/		"Contratado",
/*	6	*/		"Sem avaliação",
);

?>